# For configuration options see: https://grafana.com/docs/loki/latest/send-data/promtail/configuration/

scrape_configs:
  - job_name: default
    static_configs:
      - targets:
          - localhost
        labels:
          __dynamic_labels__
          host: ${PROMTAIL_LABEL_HOST}
          __path__: ${PROMTAIL_SCRAPE_PATH}

server:
  disable: true

positions:
  filename: ${PROMTAIL_TMP_PATH}/positions.yaml

clients:
  - url: ${PROMTAIL_CLIENT_URL}
    batchwait: 1s
    batchsize: 1048576
    follow_redirects: false
    backoff_config:
      min_period: 500ms
      max_period: 5m0s
      max_retries: 10
    timeout: 10s
    tenant_id: ${PROMTAIL_CLIENT_TENANT_ID}
    basic_auth:
      username: ${PROMTAIL_BASIC_AUTH_USERNAME}
      password: ${PROMTAIL_BASIC_AUTH_PASSWORD}
